version: "3.7"
services:
  scraper:
    container_name: scraper
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./data:/app/data
    working_dir: /app
    command: python /app/src/explore.py
